### ISSUE TITLE
V3 SHA missing

### ISSUE THREAD

**Issue by daxelrod** [pikvm/site#2]
https://pikvm.org/download.html links to https://pikvm.org/images/v3-hdmi-rpi4.img.bz2.sha1 for the SHA-1 of the v3 image, but the latter URL results in a 404. All other SHA-1s appear to be present.

I haven't tested an image build of v3 yet, so I'm not sure if the v3 process doesn't yet produce a SHA-1 or if it just hasn't been uploaded.

Thank you!

**Comment by mdevaev** [comment]
Fixed, thanks!
